inherit_gem:
  rubocop-g2:
    - config/ruby/default.yml

require:
  - rubocop-rspec
  - rubocop-g2

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false
