inherit_gem:
  rubocop-g2:
    - config/ruby/default.yml

require:
  - rubocop-rspec
  - rubocop-g2

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
    - gemfiles/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/slack_logger/post_message_spec.rb
