version: 2.1

orbs:
  ruby: g2crowd/ruby@0.0.17

workflows:
  version: 2
  build:
    jobs:
      - ruby/build:
          context: g2crowd-global
          ruby: "3.0.2"
          bundler-version: "2.2.22"
          setup-database: false
