inherit_gem:
  rubocop-g2:
    - config/rspec/default.yml

require:
  - rubocop-rspec

inherit_from:
  - ../.rubocop.yml

RSpec/MultipleExpectations:
  Enabled: false

Style/RescueModifier:
  Enabled: false
